version: "3.8" 

services: #Quais sao os servicos
  site: #Site
    image: developer10/site # Imagem docker do site
    deploy:
      replicas: 5 # Quantidade de replicas
      placement:
        constraints: [node.role == manager] # Quem recebe as informacoes (trabalhadores ou administradores)
    ports:
      - 3000:80 # Determinar qual a porta desse servico
    depends_on:
      - db # Determinar de qual servico este e dependente
  db: # Banco de dados
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432 
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    deploy:
      placement:
        constraints: [node.role == manager] 
  visualizer: # Visualiza o que cada maquina esta fazendo
    image: dockersamples/visualizer:stable
    ports:
    - "8888:8080"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]        

volumes:
  postgres_data:
