version: "3.8" 

services: #Quais sao os servicos
  site: #Site
    image: mettainnovations/app_galeria:latest # Imagem docker do site
    deploy:
      replicas: 2 # Quantidade de replicas
      placement:
        constraints: [node.role == manager] # Quem recebe as informacoes (trabalhadores ou administradores)
    ports:
      - 3000:80 # Determinar qual a porta desse servico
    depends_on:
      - db # Determinar de qual servico este e dependente
  db: # Banco de dados
    image: mysql/mysql-server:8.0
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test2019
    ports:
      - 3306:3306 
    volumes:
      - mysql_data:/home/developer/workspace
    deploy:
      placement:
        constraints: [node.role == manager] 
  visualizer: # Visualiza o que cada maquina esta fazendo
    image: dockersamples/visualizer:stable
    ports:
    - "8888:8080"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]        

volumes:
  postgres_data:
